<?php

/**
 * Persistence driver configuration.
 *
 * Switch the active driver by changing 'driver' to one of: 'json', 'sqlite', 'mysql'.
 * Each driver reads its own connection block from 'connections'.
 *
 * This file contains the application defaults.
 * The installer generates config/database.local.php with actual credentials,
 * which is merged here and must NOT be committed to version control.
 */

$config = [

    // Active driver: 'json' | 'sqlite' | 'mysql'
    'driver' => 'sqlite',

    'connections' => [

        'json' => [
            'path' => storage_path('app/database.json'),
        ],

        'sqlite' => [
            'path' => storage_path('app/database.sqlite'),
        ],

        'mysql' => [
            'host'      => env('DB_HOST', '127.0.0.1'),
            'port'      => (int) env('DB_PORT', 3306),
            'database'  => env('DB_DATABASE', 'kintai'),
            'username'  => env('DB_USERNAME', 'root'),
            'password'  => env('DB_PASSWORD', ''),
            'charset'   => 'utf8mb4',
            'collation' => 'utf8mb4_unicode_ci',
            'prefix'    => '',
        ],

    ],

];

// Merge local overrides generated by the installer (credentials, selected driver).
// This file is machine-generated and must be excluded from version control.
$localConfig = __DIR__ . '/database.local.php';
if (file_exists($localConfig)) {
    $config = array_replace_recursive($config, require $localConfig);
}

return $config;
